spring:
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common
---

spring:
  config:
    activate:
      on-profile: common
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
admin:
  email: ${ADMIN1_EMAIL}
jwt:
  key:
    secret: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 720

cloud:
  aws:
    s3:
      bucket: be-main-15
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false

---
spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test;

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${G_CLIENT_ID}
            clientSecret: ${G_CLIENT_SECRET}
            scope:
              - email
              - profile
          naver:
            clientId: ${N_CLIENT_ID}
            clientSecret: ${N_CLIENT_SECRET}
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: "http://localhost:8080/login/oauth2/code/naver"
            scope:
              - nickname
              - email
              - profile_image
            clientName: Naver
          kakao:
            clientId: ${K_CLIENT_ID}
            clientSecret: ${K_CLIENT_SECRET}
            clientAuthenticationMethod: POST
            authorizationGrantType: authorization_code
            redirectUri: "http://localhost:8080/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            clientName: Kakao
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${TODO_MYSQL_HOST}:${TODO_MYSQL_PORT}/${TODO_DATA_BASE_NAME}?useSSL=false
    username: ${TODO_MYSQL_USER_NAME}
    password: ${TODO_MYSQL_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${G_CLIENT_ID}
            clientSecret: ${G_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirectUri: "https://serverbookvillage.kro.kr/login/oauth2/code/google"
          naver:
            clientId: ${N_CLIENT_ID}
            clientSecret: ${N_CLIENT_SECRET}
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: "https://serverbookvillage.kro.kr/login/oauth2/code/naver"
            scope:
              - nickname
              - email
              - profile_image
            clientName: Naver
          kakao:
            clientId: ${K_CLIENT_ID}
            clientSecret: ${K_CLIENT_SECRET}
            clientAuthenticationMethod: POST
            authorizationGrantType: authorization_code
            redirectUri: "https://serverbookvillage.kro.kr/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            clientName: Kakao
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id